export interface Location {
    id?: number;  // Assuming the `id` is automatically generated by the server
    sensorId: number;
    name: string;
    description?: string;
  }

  export interface Measurement {
    id?: number;  // Assuming the `id` is automatically generated by the server x
    sensorId: number;
    timestamp: string;  // LocalDateTime is mapped to string in JSON (ISO 8601 format) (sometimes)
    temperature: number;
    humidity: number;
    pressure: number;
  }
  
  export interface Sensor {
    id?: number;  // Assuming the `id` is automatically generated by the server
    type: string;
    model?: string;
    installationDate: string;  // LocalDateTime is mapped to string in JSON (ISO 8601 format)
    status: boolean;
  }
  